// <auto-generated />
using System;
using IoTHomeAssistant.Infrastructure.EntityConfigurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IoTHomeAssistant.Infrastructure.Migrations
{
    [DbContext(typeof(IoTDbContext))]
    [Migration("20211123155041_Change_JobCondition_Entity")]
    partial class Change_JobCondition_Entity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Area");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.Command", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Command");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.CommandValueType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommandId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Max")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Min")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommandId")
                        .IsUnique();

                    b.ToTable("CommandValueType");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.CommandValueTypeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommandValueTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommandValueTypeId");

                    b.ToTable("CommandValueTypeItem");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Device");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.DeviceCommand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommandId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommandId");

                    b.HasIndex("DeviceId");

                    b.ToTable("DeviceCommand");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.DeviceEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("EventId");

                    b.ToTable("DeviceEvent");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.DeviceTypeCommand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommandId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommandId");

                    b.ToTable("DeviceTypeCommand");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.DeviceTypeEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("DeviceTypeEvent");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.EventValueType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Max")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Min")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("EventValueType");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.EventValueTypeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventValueTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventValueTypeId");

                    b.ToTable("EventValueTypeItem");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.Icon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Icon");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.Job", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("JobTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Succeed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobTaskId");

                    b.ToTable("Job");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.JobTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JobTask");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.JobTaskCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Operation")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SensorId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TriggeredEventId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TriggeredTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobTaskId");

                    b.HasIndex("TriggeredTaskId");

                    b.ToTable("JobTaskCondition");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.JobTaskExecution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CommandId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TriggeredTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WaitSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobTaskId");

                    b.HasIndex("TriggeredTaskId");

                    b.ToTable("JobTaskExecution");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.MqttBroker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseCredentials")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MqttBroker");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.Plugin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeviceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DockerImageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DockerImageSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Plugin");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.PluginConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<int>("PluginId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PluginId");

                    b.ToTable("PluginConfiguration");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.PluginDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExtDeviceRef")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PluginId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("PluginId");

                    b.ToTable("PluginDevice");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.PluginDeviceConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PluginConfigurationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PluginDeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PluginConfigurationId");

                    b.HasIndex("PluginDeviceId");

                    b.ToTable("PluginDeviceConfiguration");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.WidgetItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AreaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IconId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JobTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<byte>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SymbolAfter")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("EventId");

                    b.HasIndex("IconId");

                    b.ToTable("WidgetItem");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.CommandValueType", b =>
                {
                    b.HasOne("IoTHomeAssistant.Domain.Entities.Command", "Command")
                        .WithOne("ValueType")
                        .HasForeignKey("IoTHomeAssistant.Domain.Entities.CommandValueType", "CommandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Command");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.CommandValueTypeItem", b =>
                {
                    b.HasOne("IoTHomeAssistant.Domain.Entities.CommandValueType", "CommandValueType")
                        .WithMany("Items")
                        .HasForeignKey("CommandValueTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommandValueType");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.DeviceCommand", b =>
                {
                    b.HasOne("IoTHomeAssistant.Domain.Entities.Command", "Command")
                        .WithMany()
                        .HasForeignKey("CommandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IoTHomeAssistant.Domain.Entities.Device", "Device")
                        .WithMany("DeviceCommands")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Command");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.DeviceEvent", b =>
                {
                    b.HasOne("IoTHomeAssistant.Domain.Entities.Device", "Device")
                        .WithMany("DeviceEvents")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IoTHomeAssistant.Domain.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.DeviceTypeCommand", b =>
                {
                    b.HasOne("IoTHomeAssistant.Domain.Entities.Command", "Command")
                        .WithMany()
                        .HasForeignKey("CommandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Command");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.DeviceTypeEvent", b =>
                {
                    b.HasOne("IoTHomeAssistant.Domain.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.EventValueType", b =>
                {
                    b.HasOne("IoTHomeAssistant.Domain.Entities.Event", "Event")
                        .WithOne("ValueType")
                        .HasForeignKey("IoTHomeAssistant.Domain.Entities.EventValueType", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.EventValueTypeItem", b =>
                {
                    b.HasOne("IoTHomeAssistant.Domain.Entities.EventValueType", "EventValueType")
                        .WithMany("Items")
                        .HasForeignKey("EventValueTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventValueType");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.Job", b =>
                {
                    b.HasOne("IoTHomeAssistant.Domain.Entities.JobTask", "JobTask")
                        .WithMany()
                        .HasForeignKey("JobTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobTask");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.JobTaskCondition", b =>
                {
                    b.HasOne("IoTHomeAssistant.Domain.Entities.JobTask", "JobTask")
                        .WithMany("Conditions")
                        .HasForeignKey("JobTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IoTHomeAssistant.Domain.Entities.JobTask", "TriggeredTask")
                        .WithMany()
                        .HasForeignKey("TriggeredTaskId");

                    b.Navigation("JobTask");

                    b.Navigation("TriggeredTask");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.JobTaskExecution", b =>
                {
                    b.HasOne("IoTHomeAssistant.Domain.Entities.JobTask", "JobTask")
                        .WithMany("Executions")
                        .HasForeignKey("JobTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IoTHomeAssistant.Domain.Entities.JobTask", "TriggeredTask")
                        .WithMany()
                        .HasForeignKey("TriggeredTaskId");

                    b.Navigation("JobTask");

                    b.Navigation("TriggeredTask");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.PluginConfiguration", b =>
                {
                    b.HasOne("IoTHomeAssistant.Domain.Entities.Plugin", "Plugin")
                        .WithMany("Configurations")
                        .HasForeignKey("PluginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plugin");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.PluginDevice", b =>
                {
                    b.HasOne("IoTHomeAssistant.Domain.Entities.Device", "Device")
                        .WithOne("PluginDevice")
                        .HasForeignKey("IoTHomeAssistant.Domain.Entities.PluginDevice", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IoTHomeAssistant.Domain.Entities.Plugin", "Plugin")
                        .WithMany()
                        .HasForeignKey("PluginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Plugin");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.PluginDeviceConfiguration", b =>
                {
                    b.HasOne("IoTHomeAssistant.Domain.Entities.PluginConfiguration", "PluginConfiguration")
                        .WithMany()
                        .HasForeignKey("PluginConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IoTHomeAssistant.Domain.Entities.PluginDevice", "PluginDevice")
                        .WithMany("Configurations")
                        .HasForeignKey("PluginDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PluginConfiguration");

                    b.Navigation("PluginDevice");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.WidgetItem", b =>
                {
                    b.HasOne("IoTHomeAssistant.Domain.Entities.Area", "Area")
                        .WithMany("Widgets")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IoTHomeAssistant.Domain.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId");

                    b.HasOne("IoTHomeAssistant.Domain.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId");

                    b.HasOne("IoTHomeAssistant.Domain.Entities.Icon", "Icon")
                        .WithMany()
                        .HasForeignKey("IconId");

                    b.Navigation("Area");

                    b.Navigation("Device");

                    b.Navigation("Event");

                    b.Navigation("Icon");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.Area", b =>
                {
                    b.Navigation("Widgets");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.Command", b =>
                {
                    b.Navigation("ValueType");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.CommandValueType", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.Device", b =>
                {
                    b.Navigation("DeviceCommands");

                    b.Navigation("DeviceEvents");

                    b.Navigation("PluginDevice");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.Event", b =>
                {
                    b.Navigation("ValueType");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.EventValueType", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.JobTask", b =>
                {
                    b.Navigation("Conditions");

                    b.Navigation("Executions");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.Plugin", b =>
                {
                    b.Navigation("Configurations");
                });

            modelBuilder.Entity("IoTHomeAssistant.Domain.Entities.PluginDevice", b =>
                {
                    b.Navigation("Configurations");
                });
#pragma warning restore 612, 618
        }
    }
}
